1367437697046	Rename resource 'datastore.py'
